export default [
  {
    id: 1,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic62.gif`,
    title: 'Garnet',
    price: '12',
    description: 'Awesome item from Glassy brand',
    colors: ['#00b3c6', '#50e3c2', '#fa4a86'],
    new: true,
  },
  {
    id: 2,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic66.gif`,
    title: 'Ruby',
    price: '17',
    description: 'Awesome item from Glassy brand',
    colors: ['#d4d4d4', '#5ff4d3', '#f7a9c4'],
    new: true,
  },
  {
    id: 3,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic67.gif`,
    title: 'Amethyst',
    price: '17',
    description: 'Awesome item from Glassy brand',
    colors: ['#fa93bd'],
    sale: true,
    oldPrice: '23',
  },
  {
    id: 4,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic68.gif`,
    title: 'Diamond',
    price: '16',
    description: 'Awesome item from Glassy brand',
    colors: ['#c6890a', '#faee5a'],
  },
  {
    id: 5,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic69.gif`,
    title: 'Bulldog Pillow',
    price: '17',
    description: 'Awesome item from Glassy brand',
    colors: ['#fa93bd'],
    sale: true,
    oldPrice: '23',
  },
  // Relics
  {
    id: 6,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic65.jpg`,
    title: 'Digital Mamoth',
    price: '16',
    description: 'Awesome item from Glassy brand',
    colors: ['#c6890a', '#faee5a'],
  },
  {
    id: 7,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic64.jpg`,
    title: 'Pushinas Keep',
    price: '120',
    description: 'Awesome item from Glassy brand',
    colors: ['#00b3c6', '#50e3c2', '#fa4a86'],
    new: true,
  },
  {
    id: 8,
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/pic63.jpg`,
    title: 'Geisha Chronology',
    price: '17',
    description: 'Awesome item from Glassy brand',
    colors: ['#d4d4d4', '#5ff4d3', '#f7a9c4'],
    new: true,
  },
];
