// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    name: 'Garnet',
    type: 'garnet',
    symbol: 'GEM',
    description: 'Put on your brave faces and become a warrior by using Garnet Gem, strengthening your magical powers to shift the odds in your favor. Victory always falls in the hands of Brave.',
    about: 'Garnet Gem is equivalent to 500 USDT which unlocks Sphynx Slots Machine along with 250 Supraorbs Casino Chips to start your magical journey.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmVCwMtKGPjbEg32sxVkQGsLQUhwP2ox58cFxJSYFhKRY1',
    externalUrl: 'https://ipfs.io/ipfs/QmVCwMtKGPjbEg32sxVkQGsLQUhwP2ox58cFxJSYFhKRY1',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '500',
    weiPrice: '500000000', //Require update before mainnet
    gameUnlocks: 'Sphynx Slots Machine',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: true,
    gameAssetDesc: '250 Casino Chips',
    displayUrl: '/gem/garnet',
    color: '#4ce1b6',
  },
  {
    id: 2,
    name: 'Ruby',
    type: 'ruby',
    symbol: 'GEM',
    description: 'This ruby Gem - known since ancient times for its magical powers and miracles. The diamond gem properties are so varied that it can be counted among the most vital magical stones. A ruby is recognized as a magical stone of great power that enhances all the energy on Supraorbs. ',
    about: 'Ruby Gem is equivalent to 700 USDT which unlocks Crimson Craps along with 300 Supraorbs Casino Chips to win huge jackpots every day.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmYqfvcwn3zi3eZguu5pAwdDQD2uMUHUPpM55vYQdusSWM',
    externalUrl: 'https://ipfs.io/ipfs/QmYqfvcwn3zi3eZguu5pAwdDQD2uMUHUPpM55vYQdusSWM',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '600',
    weiPrice: '600000000',
    gameUnlocks: 'Crimson Craps',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: true,
    gameAssetDesc: '300 Supra Casino Chips',
    displayUrl: '/gem/ruby',
    color: '#f6da6e',
  },
  {
    id: 3,
    name: 'Amethyst',
    type: 'amethyst',
    symbol: 'GEM',
    description: 'Feel the divine power of Amethyst Gem and win ultimate streaks on Supraorbs casino that will change your life. Amethyst is used as a shielding amulet, and it nourishes your winnings.',
    about: 'Amethyst Gem is equivalent to 700 USDT which unlocks Cryptic Human Roullette along with 350 Supraorbs Casino Chips to win untimate streaks on Supraorbs.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmUzuvgptjcfrNBXuW1tD5YU2da1hhBhh4B21wqfZkqRFP',
    externalUrl: 'https://ipfs.io/ipfs/QmUzuvgptjcfrNBXuW1tD5YU2da1hhBhh4B21wqfZkqRFP',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '700',
    weiPrice: '700000000',
    gameUnlocks: 'Cryptic Human Roullette',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: true,
    gameAssetDesc: '350 Supra Casino Chips',
    displayUrl: '/gem/amethyst',
    color: '#f6da6e',
  },
  {
    id: 4,
    name: 'Emerald',
    type: 'emerald',
    symbol: 'GEM',
    description: 'Emerald is a mysterious gem that boosts your confidence and helps players predict the future, restores your luck, and drives you towards winning streaks. Its for those who wish to learn the secrets of magic and penetrate the future.',
    about: 'Emerald Gem is equivalent to 800 USDT which unlocks Skylark Baccarat along with 400 Supraorbs Casino Chips to predict the future on Supraorbs.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmUBfXRfvdaLd74NGMu8rAEtGdiRY3ZyzsSVaZJR1RTF5P',
    externalUrl: 'https://ipfs.io/ipfs/QmUBfXRfvdaLd74NGMu8rAEtGdiRY3ZyzsSVaZJR1RTF5P',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '800',
    weiPrice: '800000000',
    gameUnlocks: 'Skylark Baccarat',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: true,
    gameAssetDesc: '400 Supra Casino Chips',
    displayUrl: '/gem/emerald',
    color: '#ff4861',
  },
  {
    id: 5,
    name: 'Opal',
    type: 'opal',
    symbol: 'GEM',
    description: 'Opal is the most unpredictable stone, a symbol of ever-changing fortune. It holds the mystical power of all colors of the spectrum and shines in the darkness. The favorite stone of magicians and alchemists around the world. At once, it displays the piercing fire of the ruby, the purple brilliancy of amethyst, and the sea-green emerald, the whole blended and refulgent with a brightness that is quite incredible.',
    about: 'Coming Soon!',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmQqWaJPeioySUukSXoA2bPQeaBLb6J1xqg9vigXgEgq6H',
    externalUrl: 'https://ipfs.io/ipfs/QmQqWaJPeioySUukSXoA2bPQeaBLb6J1xqg9vigXgEgq6H',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '900',
    weiPrice: '900000000',
    gameUnlocks: 'Available Soon',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: false,
    gameAssetDesc: '450 Supra Casino Chips',
    displayUrl: '/gem/opal',
    color: '#FF33C4',
  },
  {
    id: 6,
    name: 'Diamond',
    type: 'diamond',
    symbol: 'GEM',
    description: 'This diamond Gem was known in ancient times for its surprising magical powers. The diamond gem properties are so varied that they can count among the most vital magical stones. A diamond is recognized as a magical stone of great power that enhances all the energy on Supraorbs.',
    about: 'Coming Soon!',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmUzdqfk5rThkEAfRcubdco3w8ApNvXkJm6wDPyLPxSTwn',
    externalUrl: 'https://ipfs.io/ipfs/QmUzdqfk5rThkEAfRcubdco3w8ApNvXkJm6wDPyLPxSTwn',
    gameAssets: [{ 'name': 'Creator', 'value': '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8' }],
    salePrice: '1000',
    weiPrice: '1000000000',
    gameUnlocks: 'Available Soon',
    creator: '0x7EbaFa44EC23f8210cA86065A7C54ed5CbF3b9C8',
    isAvailable: false,
    gameAssetDesc: '500 Supra Casino Chips',
    displayUrl: '/gem/diamond',
    color: '#222596 ',
  },
];
