// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id: 1,
        name: 'Sphnyx Slot Machine',
        type: 'slotMachine',
        description: '',
        about: '',
        imageUrl: '',
        isAvailable: true,
        loaderUrl: '../Games/supraorbsSlot/Build/supraorbsSlot.loader.js',
        dataUrl: '../Games/supraorbsSlot/Build/supraorbsSlot.data',
        frameworkUrl: '../Games/supraorbsSlot/Build/supraorbsSlot.framework.js',
        codeUrl: '../Games/supraorbsSlot/Build/supraorbsSlot.wasm',
    },
    {
        id: 2,
        name: 'Cryptic Human Roullette',
        type: 'roullette',
        description: '',
        about: '',
        imageUrl: '',
        isAvailable: true,
        loaderUrl: '../Games/roullette/Build/roullette.loader.js',
        dataUrl: '../Games/roullette/Build/roullette.data',
        frameworkUrl: '../Games/roullette/Build/roullette.framework.js',
        codeUrl: '../Games/roullette/Build/roullette.wasm',
    },
    {
        id: 3,
        name: 'Barracat',
        type: 'baccarat',
        description: '',
        about: '',
        imageUrl: '',
        isAvailable: true,
        loaderUrl: '../Games/barracat0_1/Build/barracart0_1.loader.js',
        dataUrl: '../Games/barracat0_1/Build/barracart0_1.data',
        frameworkUrl: '../Games/barracat0_1/Build/barracart0_1.framework.js',
        codeUrl: '../Games/barracat0_1/Build/barracart0_1.wasm',
    },
    {
        id: 4,
        name: 'Craps',
        type: 'craps',
        description: '',
        about: '',
        imageUrl: '',
        isAvailable: true,
        loaderUrl: '../Games/craps/Build/craps.loader.js',
        dataUrl: '../Games/craps/Build/craps.data',
        frameworkUrl: '../Games/craps/Build/craps.framework.js',
        codeUrl: '../Games/craps/Build/craps.wasm',
    }
]